#!/bin/bash -ex
./build mock
./build stable dp01_dc2.yaml hsc_gen2.yaml hsc.yaml sdss_stripe82_01.yml wise_00.yml
./build int dp01_dc2.yaml hsc_gen2.yaml hsc.yaml sdss_stripe82_01.yml wise_00.yml
./build idfprod dp01_dc2.yaml hsc_gen2.yaml hsc.yaml sdss_stripe82_01.yml wise_00.yml
./build idfint dp01_dc2.yaml hsc_gen2.yaml hsc.yaml sdss_stripe82_01.yml wise_00.yml
