#!/bin/bash -ex
ENVIRONMENT="$1"
GIT_TAG=`echo $GITHUB_REF | sed -E 's,refs/(heads|tags)/,,' | sed -E 's,/,-,g'`
shift

# Generate SQL files from Felis yaml files
# Place the SQL files in the sql directory, which gets
# copied into the docker image.
schema_index=0
for file in $@
do
    felis load-tap --tap-schema-index $schema_index --dry-run --engine-url=mysql:// --tap-schema-name=tap_schema --tap-tables-postfix=11 $file > sql/`basename $file`.sql
    schema_index=$((schema_index+1))
done

# Build and push docker images
docker build . -t lsstsqre/tap-schema-$ENVIRONMENT:$GIT_TAG
docker push lsstsqre/tap-schema-$ENVIRONMENT:$GIT_TAG

echo "Pushed Docker image: lsstsqre/tap-schema-$ENVIRONMENT:$GIT_TAG"

# Clean up any untracked files in the sql directory
# between the different runs of this script.
git clean -n
git clean -f sql
