#!/usr/bin/env python

import click
import yaml

@click.command()
@click.argument('felis_files', nargs=-1)
def set_schema_index(felis_files):
    for idx, f in enumerate(felis_files):
        click.echo(f"file {f}: index {idx}")

        with open(f) as orig_file:
            felis_yaml = yaml.safe_load(orig_file.read())

        felis_yaml["tap:schema_index"] = idx

        with open(f, "w") as output_file:
            output_file.write(yaml.dump(felis_yaml))

if __name__ == '__main__':
    set_schema_index()
