name: "Setup Test Environment"
description: "Setup the environment for testing in CI"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        uv pip install --system -r requirements.txt
        uv pip install --system pytest
      shell: bash

    - name: Install SDM Tools
      run: |
        uv pip install --system 'lsst-sdm-tools @ git+https://github.com/lsst/sdm_tools@main'
      shell: bash

    - name: Install yq
      run: sudo snap install yq
      shell: bash

    - name: Add test script directory to PATH
      run: echo "$(pwd)/scripts/test" >> $GITHUB_PATH
      shell: bash
