name: "Setup Test Environment"
description: "Setup the environment for testing in CI"
runs:
  using: "composite"
  steps:

    - name: Setup Python and install dependencies
      uses: ./.github/actions/setup-python

    - name: Install pytest
      run: uv pip install --system pytest
      shell: bash

    - name: Install database drivers and their dependencies
      run: uv pip install --system psycopg2-binary pymysql cryptography
      shell: bash

    - name: Install yq
      run: sudo snap install yq
      shell: bash

    - name: Add test script directory to PATH
      run: echo "$(pwd)/scripts/test" >> $GITHUB_PATH
      shell: bash
