name: "Setup Python"
description: "Setup Python"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        uv pip install --system -r requirements.txt
      shell: bash

    - name: Install sdm_schemas
      run: uv pip install --system --no-deps .
      shell: bash
