-- LSST Database Schema
-- $Author$
-- $Revision$
-- $Date$
--
-- See <http://lsstdev.ncsa.uiuc.edu/trac/wiki/Copyrights>
-- for copyright information.


CREATE TABLE AAA_Version_1_0_0 (version CHAR);


SET FOREIGN_KEY_CHECKS=0;


CREATE TABLE SimRefGalaxy
(
	refGalaxyId BIGINT NOT NULL,
	ra DOUBLE NOT NULL,
	decl DOUBLE NOT NULL,
	uMag DOUBLE NOT NULL,
	gMag DOUBLE NOT NULL,
	rMag DOUBLE NOT NULL,
	iMag DOUBLE NOT NULL,
	zMag DOUBLE NOT NULL,
	yMag DOUBLE NOT NULL,
	redshift DOUBLE NOT NULL
) ;


CREATE TABLE SimRefGalaxy_11032010
(
	refGalaxyId BIGINT NOT NULL,
	ra DOUBLE NOT NULL,
	decl DOUBLE NOT NULL,
	uMag DOUBLE NOT NULL,
	gMag DOUBLE NOT NULL,
	rMag DOUBLE NOT NULL,
	iMag DOUBLE NOT NULL,
	zMag DOUBLE NOT NULL,
	yMag DOUBLE NOT NULL,
	redshift DOUBLE NOT NULL,
	PRIMARY KEY (refGalaxyId),
	INDEX decl (decl ASC)
) ;


CREATE TABLE SimRefObject
(
	refObjectId BIGINT NOT NULL,
	isStar TINYINT NOT NULL,
	ra DOUBLE NOT NULL,
	decl DOUBLE NOT NULL,
	gLat DOUBLE NULL,
	gLon DOUBLE NULL,
	sedName CHAR(32) NULL,
	uMag DOUBLE NOT NULL,
	gMag DOUBLE NOT NULL,
	rMag DOUBLE NOT NULL,
	iMag DOUBLE NOT NULL,
	zMag DOUBLE NOT NULL,
	yMag DOUBLE NOT NULL,
	muRa DOUBLE NULL,
	muDecl DOUBLE NULL,
	parallax DOUBLE NULL,
	vRad DOUBLE NULL,
	isVar TINYINT NOT NULL,
	redshift DOUBLE NULL,
	PRIMARY KEY (refObjectId)
) ;


CREATE TABLE SimRefObject_11032010
(
	refObjectId BIGINT NOT NULL,
	isStar TINYINT NOT NULL,
	ra DOUBLE NOT NULL,
	decl DOUBLE NOT NULL,
	gLat DOUBLE NULL,
	gLon DOUBLE NULL,
	sedName CHAR(32) NULL,
	uMag DOUBLE NOT NULL,
	gMag DOUBLE NOT NULL,
	rMag DOUBLE NOT NULL,
	iMag DOUBLE NOT NULL,
	zMag DOUBLE NOT NULL,
	yMag DOUBLE NOT NULL,
	muRa DOUBLE NULL,
	muDecl DOUBLE NULL,
	parallax DOUBLE NULL,
	vRad DOUBLE NULL,
	isVar TINYINT NOT NULL,
	redshift DOUBLE NULL,
	PRIMARY KEY (refObjectId),
	INDEX decl (decl ASC)
) ;


CREATE TABLE SimRefStar
(
	refStarId BIGINT NOT NULL,
	ra DOUBLE NOT NULL,
	decl DOUBLE NOT NULL,
	gLat DOUBLE NOT NULL,
	gLon DOUBLE NOT NULL,
	sedName CHAR(32) NULL,
	uMag DOUBLE NOT NULL,
	gMag DOUBLE NOT NULL,
	rMag DOUBLE NOT NULL,
	iMag DOUBLE NOT NULL,
	zMag DOUBLE NOT NULL,
	yMag DOUBLE NOT NULL,
	muRa DOUBLE NOT NULL,
	muDecl DOUBLE NOT NULL,
	parallax DOUBLE NOT NULL,
	vRad DOUBLE NOT NULL,
	isVar TINYINT NOT NULL
) ;


CREATE TABLE SimRefStar_11032010
(
	refStarId BIGINT NOT NULL,
	ra DOUBLE NOT NULL,
	decl DOUBLE NOT NULL,
	gLat DOUBLE NOT NULL,
	gLon DOUBLE NOT NULL,
	sedName CHAR(32) NULL,
	uMag DOUBLE NOT NULL,
	gMag DOUBLE NOT NULL,
	rMag DOUBLE NOT NULL,
	iMag DOUBLE NOT NULL,
	zMag DOUBLE NOT NULL,
	yMag DOUBLE NOT NULL,
	muRa DOUBLE NOT NULL,
	muDecl DOUBLE NOT NULL,
	parallax DOUBLE NOT NULL,
	vRad DOUBLE NOT NULL,
	isVar TINYINT NOT NULL,
	PRIMARY KEY (refStarId),
	INDEX decl (decl ASC)
) ;



SET FOREIGN_KEY_CHECKS=1;
