name: Test SQLite
on:
  workflow_call:

jobs:

  test_sqlite:

    runs-on: ubuntu-latest

    steps:

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Python and install dependencies
        uses: ./.github/actions/setup-test-environment

      - name: Set engine URL
        run: echo "FELIS_ENGINE_URL=sqlite:///test.db" >> $GITHUB_ENV

      - name: Create databases
        run: create-databases.sh

      - name: Generate SQL files
        run: generate-sql-files.sh sqlite

      - name: Load SQL files
        run: load-sql.sh sqlite

      - name: Set engine URL
        run: echo "FELIS_ENGINE_URL=sqlite:///TAP_SCHEMA.db" >> $GITHUB_ENV

      - name: Load TAP_SCHEMA
        run: load-tap-schema.sh
