name: Test MySQL
on:
  workflow_call:

jobs:

  test_mysql:

    runs-on: ubuntu-latest

    # mariadb:
    #  image: mariadb:10.6.8
    services:
      mysql:
        image: mysql:8.0.39
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: rubin
          MYSQL_PASSWORD: rubin
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Check out repo
        uses: actions/checkout@v5

      - name: Setup Python and install dependencies
        uses: ./.github/actions/setup-test-environment

      - name: Grant privileges to MySQL user
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'rubin'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;" > /dev/null 2>&1

      - name: Set MySQL credentials
        run: |
          cat <<EOF > ~/.my.cnf
          [client]
          user=rubin
          password=rubin
          host=127.0.0.1
          port=3306
          EOF
          chmod 600 ~/.my.cnf

      - name: Set FELIS_ENGINE_URL
        run: echo "FELIS_ENGINE_URL=mysql+pymysql://rubin:rubin@localhost:3306" >> $GITHUB_ENV

      - name: Create databases
        run: |
          create-databases.sh

      - name: Generate SQL files
        run: |
          generate-sql-files.sh mysql

      - name: Load SQL files
        run: |
          load-sql.sh mysql

      - name: Load TAP_SCHEMA database
        run: load-tap-schema.sh
